version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ICON=${ICON}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CALLBACK_URL=${CALLBACK_URL}
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_TOPICS=${MQTT_TOPICS}
      - MQTT_BROKER_URL=${MQTT_BROKER_URL}
      - SANDBOX=${SANDBOX}
      - DISPLAY_QR_CODE=${DISPLAY_QR_CODE}
      - UPDATE_INTERVAL=${UPDATE_INTERVAL}
      - AWTRIX_SETTINGS=${AWTRIX_SETTINGS}
    volumes:
      - ./data:/usr/src/app/data
